services:
  - type: web
    name: article-similarity-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dash.py --server.port=$PORT --server.address=0.0.0.0 --server.enableCORS=false --server.enableXsrfProtection=false