services:
  - type: web
    name: scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dash.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false